### ISSUE TITLE
Smart Add Not working

### ISSUE THREAD

**Issue by m2n037** [Librarika/Issues#81] opened 2014-12-30 15:04 UTC
Error in processing data, please try again.

This error message is shown when I try to add books using smart add method.
![11](https://cloud.githubusercontent.com/assets/8148440/5579592/4a1d57da-9063-11e4-925d-4560e6cebea3.JPG)

**Comment by vitalyzhakov** [comment] 2015-01-14 16:05
I have same problem.
During last 10 days I try to add about 100 books. About 20 have the same problem, list of their ISBN below:
5762500764
585585020x
5855850218
5699046240
5040881827
5040087209
517015562x
5040088825
5040099436
5852730017
5253002030
5353017269
5699113649
9785486015175
5715504198
5893550056
5780505195
5762503054
5253000135
5883880010
5660007457
5358006036
5763206274
576320283x
5763202279

**Comment by rayhan** [comment] 2015-01-19 04:24
Yes, our upstream data source doesn't have all the ISBNs information. If you know any open ISBN data source that have more searchable data, please let us know.

**Comment by nikue** [comment] 2015-01-19 16:38
I think the problem isn't the data source, but rather that there are 2 different error messages. "Our system could not find data related to this ISBN..." is very clear and not a problem. However, "Error in processing data" is cryptic and implies that the system could find the data, but wasn't able to process it for some reason. Is there a specific reason for the different messages? Thanks!

**Comment by rayhan** [comment] 2015-01-19 16:43
Well, then we must need to look into it. Thats a valuable information to look into.

**Comment by ymgrigsb** [comment] 2015-09-21 00:05
I do not know what data source you are currently using but I thought I would add what I know I have used manually (maybe they have a free API or you can somehow get the data from a resulting html page):
https://openlibrary.org/
http://www.worldcat.org/
http://lookupbyisbn.com/

**Comment by rayhan** [comment] 2015-10-01 04:01
Thanks for the advice, lookupbyisbn seems using amazon as source. openlibrary is already integrated. Will look into worldcat.org seriously. Closing this issue for now.

**Closed by rayhan** 2015-10-01 04:01 UTC
