### ISSUE TITLE
Refreshing page + other errors

### ISSUE THREAD

**Issue by vicmwa** [Librarika/Issues#473] opened 2018-03-26 09:06 UTC
1. I'm always getting the refresh page even when internet connection is ok. Please advise
2. Do you have an android version?
3. Slow loading in between pages, leading to an error

**Comment by rayhan** [comment] 2018-04-04 15:13
It seems very unlikely. Which browser do you use? 

// BR

**Comment by vicmwa** [comment] 2018-04-05 05:08
I use Google Chrome


This e-mail and any attachments may contain information that is 
confidential, legally privileged and protected by law and is intended for 
the sole use of the named recipient(s). Any unauthorized review, use, or 
disclosure or distribution is prohibited. Any liability (in negligence or 
otherwise) arising from any third party acting, or refraining from acting 
on any information contained in this email is hereby excluded. If you are 
not the intended recipient, please delete the contents and notify the 
sender immediately; do not disclose the contents to any other person, use 
it for any purpose or store or copy the information in any medium. 


For further information about Oraro & Co Advocates, please contact us 
at ACK Garden Annex, 6th Floor, 1st Ngong Avenue, P. O. Box 51236-00200, 
Nairobi, Kenya, telephone: +254 20 2710426/271580/2713636  Fax +254 20 
272709 or visit our website www.oraro.co.ke

**Comment by rayhan** [comment] 2018-07-17 17:42
Closing this issue, since we have failed to reproduced this issue on our end. Please reopen the issue if your problem is not resolved yet.

**Closed by rayhan** 2018-07-17 17:42 UTC
